---
- name: Assert kubernetes_node_type
  assert:
    that:
      - kubernetes_node_type in kubernetes_supported_node_type

- name: Ensure ca-certificates installed
  apt:
    name: ca-certificates
  state: present

- name: Ensure ca-certificates installed
  apt:
    name: ca-certificates
    state: present
  
- name: Add kubernetes key
  apt_key:
    id: '{{ kubernetes_apt_key_id }}'
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    state: present
    
- name: Add kubernetes sources list
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
  
- name: Install kubernetes (worker)
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - kubelet
    - kubernetes-cni
  when: kubernetes_node_type == 'worker'

- name: Install kubernetes (master)
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubernetes-cni
  when: kubernetes_node_type == 'master'

- name: Install kubernetes (admin)
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubeadm
    - kubernetes-cni
  when: kubernetes_node_type == 'admin'

- name: Fix network_plugin
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '\s\$KUBELET_NETWORK_ARGS'
    replace: ''

- name: Restart kubelet daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: kubelet

- name: Init cluster
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_ssh_host }} --kubernetes-version stable-1.8 | grep 'kubeadm join'"
  register: kubernetes_join
  when:
    - kubernetes_init_cluster
    - kubernetes_node_type == 'admin' or kubernetes_node_type == 'master'

- debug: msg={{ kubernetes_join.stdout }}
  when: kubernetes_join is defined

- name: Fetching cluster config to local machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: /tmp/
    flat: yes
  when:
    - kubernetes_copy_config is defined
    - kubernetes_copy_config
    - kubernetes_node_type == 'admin' or kubernetes_node_type == 'master'
